### ISSUE TITLE
String index out of range: 3

### ISSUE THREAD

**Issue by valentinobjectivecorporationuk** [cefolger/needsmoredojo#178]
String index out of range: 3
java.lang.StringIndexOutOfBoundsException: String index out of range: 3
    at java.lang.String.charAt(String.java:646)
    at com.chrisfolger.needsmoredojo.core.amd.naming.NameResolver.defineToParameter(NameResolver.java:79)
    at com.chrisfolger.needsmoredojo.core.amd.naming.NameResolver.defineToParameter(NameResolver.java:16)
    at com.chrisfolger.needsmoredojo.intellij.inspections.MismatchedImportsInspection.addProblemsForBlock(MismatchedImportsInspection.java:129)
    at com.chrisfolger.needsmoredojo.intellij.inspections.MismatchedImportsInspection.checkFile(MismatchedImportsInspection.java:197)
    at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:151)
    at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
    at com.intellij.lang.javascript.psi.impl.JSFileImpl.accept(JSFileImpl.java:120)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:309)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:304)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by atomes** [comment]
I get similar when trying to add new amd import
String index out of range: -13
java.lang.StringIndexOutOfBoundsException: String index out of range: -13
    at java.lang.String.substring(String.java:1919)
    at com.chrisfolger.needsmoredojo.core.amd.importing.ImportResolver.getChoicesFromFiles(ImportResolver.java:85)
    at com.chrisfolger.needsmoredojo.core.amd.importing.ImportResolver.getChoicesFromFiles(ImportResolver.java:185)
    at com.chrisfolger.needsmoredojo.core.amd.importing.ImportResolver.getPossibleDojoImports(ImportResolver.java:283)
    at com.chrisfolger.needsmoredojo.core.amd.importing.ImportResolver.getPossibleDojoImports(ImportResolver.java:303)
    at com.chrisfolger.needsmoredojo.intellij.actions.AddNewImportAction.actionPerformed(AddNewImportAction.java:63)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.ide.actions.GotoActionAction$5.run(GotoActionAction.java:212)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
