### ISSUE TITLE
Plugin incompatible with new versions of WebStorm 

### ISSUE THREAD

**Issue by SergKam** [cefolger/needsmoredojo#180]
Plugin incompatible with new versions of WebStorm.
Only adding new module seems to be working, all other functions like navigation, cleanup unused, etc  not working.

WebStorm WS-144.3600.14
Build #WS-144.3600, built on February 3, 2016
JRE: 1.8.0_76-release-b17 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

please look at this stacktarce

```
com.intellij.lang.javascript.psi.JSFunctionExpression.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameter;
java.lang.NoSuchMethodError: com.intellij.lang.javascript.psi.JSFunctionExpression.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameter;
    at com.chrisfolger.needsmoredojo.core.amd.define.DefineResolver.addDefinesAndParametersOfImportBlock(DefineResolver.java:44)
    at com.chrisfolger.needsmoredojo.intellij.inspections.MismatchedImportsInspection.addProblemsForBlock(MismatchedImportsInspection.java:73)
    at com.chrisfolger.needsmoredojo.intellij.inspections.MismatchedImportsInspection.checkFile(MismatchedImportsInspection.java:197)
    at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
    at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
    at com.intellij.lang.javascript.psi.impl.JSFileImpl.accept(JSFileImpl.java:122)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:128)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



java.lang.NoSuchMethodError: com.intellij.lang.javascript.psi.JSFunctionExpression.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameter;
    at com.chrisfolger.needsmoredojo.core.amd.define.DefineResolver.addDefinesAndParametersOfImportBlock(DefineResolver.java:44)
    at com.chrisfolger.needsmoredojo.intellij.inspections.MismatchedImportsInspection.addProblemsForBlock(MismatchedImportsInspection.java:73)
    at com.chrisfolger.needsmoredojo.intellij.inspections.MismatchedImportsInspection.checkFile(MismatchedImportsInspection.java:197)
    at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
    at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
    at com.intellij.lang.javascript.psi.impl.JSFileImpl.accept(JSFileImpl.java:122)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:128)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



java.lang.NoSuchMethodError: com.intellij.lang.javascript.psi.JSFunctionExpression.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameter;
    at com.chrisfolger.needsmoredojo.core.amd.define.DefineResolver.addDefinesAndParametersOfImportBlock(DefineResolver.java:44)
    at com.chrisfolger.needsmoredojo.core.amd.importing.UnusedImportsRemover.filterUsedModules(UnusedImportsRemover.java:135)
    at com.chrisfolger.needsmoredojo.intellij.inspections.UnusedImportsInspection.checkFile(UnusedImportsInspection.java:72)
    at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
    at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
    at com.intellij.lang.javascript.psi.impl.JSFileImpl.accept(JSFileImpl.java:122)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:128)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



java.lang.NoSuchMethodError: com.intellij.lang.javascript.psi.JSFunctionExpression.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameter;
    at com.chrisfolger.needsmoredojo.core.amd.define.DefineResolver.addDefinesAndParametersOfImportBlock(DefineResolver.java:44)
    at com.chrisfolger.needsmoredojo.core.amd.importing.UnusedImportsRemover.filterUsedModules(UnusedImportsRemover.java:135)
    at com.chrisfolger.needsmoredojo.intellij.inspections.UnusedImportsInspection.checkFile(UnusedImportsInspection.java:72)
    at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
    at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
    at com.intellij.lang.javascript.psi.impl.JSFileImpl.accept(JSFileImpl.java:122)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:128)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by tgeorges** [comment]
@SergKam Did you make a patch to make it work ?

**Comment by SergKam** [comment]
@tgeorges No, sorry,  I'm not a java developer now. I've just downgraded WebStorm to v11 to make this plugin work.

**Comment by scbird** [comment]
I've been in touch with JetBrains' support and their developers are looking into providing backward compatibility, so hopefully in a release or two this plugin will work again.
