### ISSUE TITLE
Error with version 0.7 and Webstorm 2016.1.1

### ISSUE THREAD

**Issue by savola28** [cefolger/needsmoredojo#182]
I updated my Webstorm and Needs More Dojo plugin stopped working. I tried to reorder imports (Ctrl+Shift+O) and I got error:

```
com.intellij.lang.javascript.psi.JSFunctionExpression.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameter;
java.lang.NoSuchMethodError: com.intellij.lang.javascript.psi.JSFunctionExpression.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameter;
                             at com.chrisfolger.needsmoredojo.core.amd.define.DefineResolver.addDefinesAndParametersOfImportBlock(DefineResolver.java:44)
                             at com.chrisfolger.needsmoredojo.intellij.actions.OrganizeAMDImportsAction$1$1.run(OrganizeAMDImportsAction.java:51)
                             at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
                             at com.chrisfolger.needsmoredojo.intellij.actions.OrganizeAMDImportsAction$1.run(OrganizeAMDImportsAction.java:38)
                             at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
                             at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
                             at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
                             at com.chrisfolger.needsmoredojo.intellij.actions.OrganizeAMDImportsAction.actionPerformed(OrganizeAMDImportsAction.java:35)
                             at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
                             at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
                             at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:361)
                             at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.e(IdeKeyEventDispatcher.java:297)
                             at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:221)
                             at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
                             at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
                             at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                             at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                             at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                             at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                             at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                             at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by SergKam** [comment]
Duplicate https://github.com/cefolger/needsmoredojo/issues/180
and the fix is waiting https://github.com/cefolger/needsmoredojo/pull/181
