### ISSUE TITLE
Exception on WebStorm 2017.3.3 (getParameters() - NoSuchMethodError)

### ISSUE THREAD

**Issue by heypano** [cefolger/needsmoredojo#187]
Happens any time I open a project with needs more dojo configured

Error:

```Worker exited due to exception: com.intellij.lang.javascript.psi.JSFunctionExpression.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameterItemWithSource;
java.lang.NoSuchMethodError: com.intellij.lang.javascript.psi.JSFunctionExpression.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameterItemWithSource;
	at com.chrisfolger.needsmoredojo.core.amd.psi.AMDPsiUtil.resolveReferencedDefine(AMDPsiUtil.java:355)
	at com.chrisfolger.needsmoredojo.intellij.reference.ImportGotoDeclarationHandler.getGotoDeclarationTargets(ImportGotoDeclarationHandler.java:49)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:287)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2300(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.b(CtrlMouseHandler.java:837)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$3100(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:817)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:236)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.NoSuchMethodError: com.intellij.lang.javascript.psi.JSFunctionExpression.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameterItemWithSource;
	at com.chrisfolger.needsmoredojo.core.amd.psi.AMDPsiUtil.resolveReferencedDefine(AMDPsiUtil.java:355)
	at com.chrisfolger.needsmoredojo.intellij.reference.ImportGotoDeclarationHandler.getGotoDeclarationTargets(ImportGotoDeclarationHandler.java:49)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:287)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2300(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.b(CtrlMouseHandler.java:837)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$3100(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:817)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:236)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.NoSuchMethodError: com.intellij.lang.javascript.psi.JSFunctionExpression.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameterItemWithSource;
	at com.chrisfolger.needsmoredojo.core.amd.psi.AMDPsiUtil.resolveReferencedDefine(AMDPsiUtil.java:355)
	at com.chrisfolger.needsmoredojo.intellij.reference.ImportGotoDeclarationHandler.getGotoDeclarationTargets(ImportGotoDeclarationHandler.java:49)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:287)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2300(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.b(CtrlMouseHandler.java:837)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$3100(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:817)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:236)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by comxd** [comment]
0.8.1 work fine: https://github.com/TomDevs/needsmoredojo/blob/master/dist/needsmoredojo-0.8.1.jar
