### ISSUE TITLE
class cast exception with a declare statement with a single mixin (not in an array) 

### ISSUE THREAD

**Issue by cefolger** [cefolger/needsmoredojo#48]
Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=65,keyText=A,keyChar='a',keyLocation=KEY_LOCATION_STANDARD,rawCode=65,primaryLevelUnicode=97,scancode=30,extendedKeyCode=0x41] on frame0: com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl cannot be cast to com.intellij.lang.javascript.psi.JSObjectLiteralExpression
java.lang.ClassCastException: com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl cannot be cast to com.intellij.lang.javascript.psi.JSObjectLiteralExpression
    at com.chrisfolger.needsmoredojo.core.util.DeclareUtil.getDeclareStatementFromParsedStatement(DeclareUtil.java:85)
    at com.chrisfolger.needsmoredojo.core.util.DeclareUtil.getDeclareStatementFromParsedStatement(DeclareUtil.java:47)
    at com.chrisfolger.needsmoredojo.core.util.TemplatedWidgetUtil$1.run(TemplatedWidgetUtil.java:29)
    at com.chrisfolger.needsmoredojo.core.amd.DeclareFinder$1.visitJSReturnStatement(DeclareFinder.java:49)
    at com.intellij.lang.javascript.psi.impl.JSReturnStatementImpl.accept(JSReturnStatementImpl.java:45)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:70)
    at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:15)
    at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:201)
    at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSSourceElement(JSElementVisitor.java:205)
    at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSStatement(JSElementVisitor.java:213)
    at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSBlock(JSElementVisitor.java:181)
    at com.intellij.lang.javascript.psi.impl.JSBlockStatementImpl.accept(JSBlockStatementImpl.java:68)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:70)
    at com.chrisfolger.needsmoredojo.core.amd.DeclareFinder$2.visitJSCallExpression(DeclareFinder.java:72)
    at com.intellij.lang.javascript.psi.impl.JSCallExpressionImpl.accept(JSCallExpressionImpl.java:63)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:70)
    at com.intellij.lang.javascript.psi.JSRecursiveElementVisitor.visitElement(JSRecursiveElementVisitor.java:15)
    at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSElement(JSElementVisitor.java:201)
    at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSSourceElement(JSElementVisitor.java:205)
    at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSStatement(JSElementVisitor.java:213)
    at com.intellij.lang.javascript.psi.JSElementVisitor.visitJSExpressionStatement(JSElementVisitor.java:173)
    at com.intellij.lang.javascript.psi.impl.JSExpressionStatementImpl.accept(JSExpressionStatementImpl.java:49)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
    at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:756)
    at com.chrisfolger.needsmoredojo.core.util.TemplatedWidgetUtil.findTemplatePath(TemplatedWidgetUtil.java:26)
    at com.chrisfolger.needsmoredojo.intellij.actions.JumpToAttachPointAction.actionPerformed(JumpToAttachPointAction.java:41)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:342)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:281)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:494)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by cefolger** [comment]
see dijit/MenuBar
