### ISSUE TITLE
noclassdeffound when loading in intellij 

### ISSUE THREAD

**Issue by cefolger** [cefolger/needsmoredojo#67]
com.chrisfolger.needsmoredojo.intellij.components.DojoSettingsDetectionComponent@137a727: com/chrisfolger/needsmoredojo/intellij/components/DojoSettingsDetectionComponent$1
java.lang.NoClassDefFoundError: com/chrisfolger/needsmoredojo/intellij/components/DojoSettingsDetectionComponent$1
    at com.chrisfolger.needsmoredojo.intellij.components.DojoSettingsDetectionComponent.projectOpened(DojoSettingsDetectionComponent.java:56)
    at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:415)
    at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:75)
    at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:451)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$2.projectOpened(ProjectManagerImpl.java:153)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl.java:1030)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:408)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:473)

**Comment by cefolger** [comment]
apparently idea 12.0.1 does not have NotificationListener.Adapter, while 12.1 does.
